[package]
name = "camera-streamer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rscam = "0.5.5"
tungstenite = "0.17.3"
clap = { version = "3.2.16", features = ["derive"] }
image = "0.24.3"