# Server configuration options
[server]
#host = "localhost"  # The host address to bind to
port = 11571  # The port to bind to

# Security options
[wss]
enabled = false  # Enables Secure WebSockets
#chain_path = "/etc/letsencrypt/live/rover.team1157.org/fullchain.pem"  # Path to certificate chain
#privkey_path = "/etc/letsencrypt/live/rover.team1157.org/privkey.pem"  # Path to private key
